# Basic
title: bladechen
subtitle: A blog-orientation theme for Jekyll
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: Vno Jekyll is a port of my Ghost theme vno.
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    # - {title: Resume, description: My Projects, url: 'http://project.onevcat.com'}
    - {title: Resume, url: 'https://github.com/bladechen/resume/blob/master/resume.md'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo:

# Social
social:
    weibo: 3189514300
    github: bladechen
    facebook: 100009302664416
    linkedin: shenglong-chen-548985100
    # twitter: onevcat
    # gplus: 107108267983477358170
    mail: chenshenglong1990@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
