# Basic
title: bladechen
subtitle: 黑暗给了我黑色的眼睛，我却用他来寻找光明
welcome_message: <a href="https://github.com/bladechen/9242" target="_blank"> UNSW AOS(高级操作系统) 项目源代码 </a>
description: 10年编程经验, Ex-acmer, 前腾讯后台开发工程师 <br> 专注于Linux C/C++ 后台开发, 分布式系统, 操作系统内核
# creator: <a href="http://onev.cat">@onevcat</a>

# url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
# cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    # - {title: Resume, description: My Projects, url: 'http://project.onevcat.com'}
    - {title: Resume, url: 'https://github.com/bladechen/resume/blob/master/resume.md'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: bladechen
    # duoshuo:

# Social
social:
    weibo: 3189514300
    github: bladechen
    facebook: 100009302664416
    linkedin: shenglong-chen-548985100
    # twitter: onevcat
    # gplus: 107108267983477358170
    mail: chenshenglong1990@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
